# Generated by Django 5.2.9 on 2025-12-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplesite',
            name='trib_name',
        ),
    ]
