# Generated by Django 5.2.9 on 2025-12-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0002_remove_samplesite_trib_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishingsite_cf',
            name='trib_name',
        ),
    ]
