# Generated by Django 5.2.9 on 2025-12-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0003_remove_fishingsite_cf_trib_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fishspecies',
            options={'ordering': ['-ranked', 'name'], 'verbose_name': '(Lookup) Fish Spp', 'verbose_name_plural': '(Lookup) Fish Spp'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': '(Lookup) Project', 'verbose_name_plural': '(Lookup) Projects'},
        ),
        migrations.AddField(
            model_name='fishspecies',
            name='ranked',
            field=models.IntegerField(blank=True, db_comment='Numeric rank for sorting fish species.', db_default=0, default=0, null=True, verbose_name='Rank'),
        ),
    ]
