# Generated by Django 5.2.9 on 2025-12-16 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0004_alter_fishspecies_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfevent',
            options={'ordering': ['-cf_date', 'fisher', 'set_num'], 'verbose_name': '(CF) Fishing Event', 'verbose_name_plural': '(CF) Fishing Events'},
        ),
        migrations.AlterModelOptions(
            name='subsample',
            options={'ordering': ['-cf_date', 'fisher', 'spp'], 'verbose_name': '(CF) Subsample', 'verbose_name_plural': '(CF) Subsamples'},
        ),
        migrations.CreateModel(
            name='RaEvent',
            fields=[
                ('event_id', models.AutoField(db_comment='ID representing the ICHP ride-along effort.', primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_date', models.DateField(db_comment='Date at which the commercial fisher Ride-Along occurred.', verbose_name='RA Date')),
                ('latitude', models.DecimalField(blank=True, db_comment='Latitude of specific location where fishing gear was deployed.', decimal_places=5, max_digits=8, null=True, verbose_name='Net LAT')),
                ('longitude', models.DecimalField(blank=True, db_comment='Longitude of specific location where fishing gear was deployed.', decimal_places=5, max_digits=8, null=True, verbose_name='Net LON')),
                ('set_num', models.SmallIntegerField(db_comment='Net or net-set number.', verbose_name='Net Set No.')),
                ('start_time', models.DateTimeField(blank=True, db_comment='Date and Time of when the net was deployed.', null=True, verbose_name='Set Time')),
                ('end_time', models.DateTimeField(blank=True, db_comment='Date and Time of when the net was retrieved.', null=True, verbose_name='Pull Time')),
                ('set_duration', models.IntegerField(blank=True, db_comment='Amount of time (in minutes) that the net was actively fishing.', null=True, verbose_name='Soak Time (min)')),
                ('gear_length', models.IntegerField(blank=True, db_comment='Total length in feet of the net used for this ride-Along event.', null=True, verbose_name='Net Length (ft)')),
                ('gear_depth', models.IntegerField(blank=True, db_comment='Total Height in feet of the net used for this ride-Along event.', null=True, verbose_name='Net Height (ft) ')),
                ('mesh_size', models.DecimalField(blank=True, db_comment='Mesh size in inches of the net used for this ride-Along event.', decimal_places=2, max_digits=5, null=True, verbose_name='Mesh Size (in)')),
                ('water_temp_f', models.DecimalField(blank=True, db_comment='Water temperature (F) recorded during the ride-along event.', decimal_places=1, max_digits=4, null=True, verbose_name='Water Temp (F)')),
                ('added_on', models.DateTimeField(auto_now_add=True, db_comment='Date-time of data input.')),
                ('added_by', models.CharField(blank=True, db_comment='name of person inputting the data.', max_length=150, null=True)),
                ('datez', models.ForeignKey(db_comment='ID referencing the date table for the ride-along date.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.dates')),
                ('fisher', models.ForeignKey(db_comment='ID of commercial fisher that completed the fishing efforts.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.fisher')),
                ('gear', models.ForeignKey(db_comment='ID of the gear type used to conduct the commercial fishing.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.gear')),
                ('observer', models.ForeignKey(db_comment='ID of agency staff that conducted the commercial ride-along.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.observer')),
                ('site', models.ForeignKey(db_comment='ID of the primary site where the ICHP fishing occured.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.fishingsite_hp')),
            ],
            options={
                'verbose_name': '(ICHP) RA Fishing Event',
                'verbose_name_plural': '(ICHP) RA Fishing Events',
                'db_table': 'ra_events',
                'db_table_comment': 'Information about the field events when agency staff accompanied ICHP fishers in order to obtain additional details about their efforts.',
                'ordering': ['-ra_date', 'fisher', 'set_num'],
            },
        ),
        migrations.CreateModel(
            name='RaCatch',
            fields=[
                ('catch_id', models.AutoField(db_comment='ID representing the results gathered during a Ride-Along event.', primary_key=True, serialize=False, verbose_name='ID')),
                ('healthy_cnt', models.IntegerField(blank=True, db_comment='Number of heathy bycatch caught and released during a ICHP ride-along effort.', default=0, null=True, verbose_name='Healthy Count')),
                ('moribund_cnt', models.IntegerField(blank=True, db_comment='Number of moribund bycatch and/or harvested Invasive Carp caught during a ICHP ride-along effort.', default=0, null=True, verbose_name='Moribund Count')),
                ('total_cnt', models.IntegerField(blank=True, db_comment='Total count of bycatch and Invasive carp caught during the ICHP ride-along effort.', default=0, null=True, verbose_name='Total Catch')),
                ('mean_length_mm', models.DecimalField(blank=True, db_comment='Estimated mean length (in millimeters) of Invasive Carp species. Calculated from RA subsamples.', decimal_places=1, max_digits=5, null=True, verbose_name='Est Mean Length (mm)')),
                ('mean_weight_g', models.DecimalField(blank=True, db_comment='Estimated mean weight (in grams) of Invasive Carp species. Calculated from RA subsamples.', decimal_places=1, max_digits=7, null=True, verbose_name='Est Mean Weight (g)')),
                ('predicted_weight_g', models.DecimalField(blank=True, db_comment='Predicted mean weight (in grams). Calculated via the a sample mean length and a length-weight regression for the population.', decimal_places=1, max_digits=7, null=True, verbose_name='Predicted Mean Weight (g)')),
                ('ss_code', models.CharField(blank=True, db_comment='Subsample identifier compiled from date, fisher_id and species_id (as YYYYMMDD.fid.sppid).', max_length=15, null=True, verbose_name='Subsample Code')),
                ('added_on', models.DateTimeField(auto_now_add=True, db_comment='Date-time of data input.')),
                ('added_by', models.CharField(blank=True, db_comment='username of person inputting the data.', max_length=150, null=True)),
                ('species', models.ForeignKey(db_comment='ID of fish species captured by ICHP fishers.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.fishspecies')),
                ('event', models.ForeignKey(db_comment='ID representing a ICHP Ride-Along event.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.raevent')),
            ],
            options={
                'verbose_name': '(ICHP) RA Catch Data',
                'verbose_name_plural': '(ICHP) RA Catch Data',
                'db_table': 'ra_catch',
                'db_table_comment': 'Catch Results of the Ride-Along events conducted with ICHP participants.',
                'ordering': ['-event__ra_date', 'event__fisher', 'event__set_num'],
            },
        ),
    ]
