# Generated by Django 5.2.9 on 2025-12-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0005_alter_cfevent_options_alter_subsample_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfcatch',
            options={'ordering': ['-event__cf_date', 'event__fisher', 'event__set_num'], 'verbose_name': '(CF) Catch Data', 'verbose_name_plural': '(CF) Catch Data'},
        ),
    ]
