# Generated by Django 5.2.9 on 2025-12-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0006_alter_cfcatch_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raevent',
            name='set_duration',
        ),
        migrations.RemoveField(
            model_name='raevent',
            name='water_temp_f',
        ),
        migrations.AlterField(
            model_name='raevent',
            name='gear_depth',
            field=models.IntegerField(blank=True, db_comment='Total Depth in feet of the net used for this ride-Along event.', null=True, verbose_name='Net Depth (ft) '),
        ),
    ]
