# Generated by Django 5.2.9 on 2025-12-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0007_remove_raevent_set_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racatch',
            options={'ordering': ['-event__ra_date', 'event__fisher', 'event__net_set', 'event__net_num'], 'verbose_name': '(ICHP) RA Catch Data', 'verbose_name_plural': '(ICHP) RA Catch Data'},
        ),
        migrations.AlterModelOptions(
            name='raevent',
            options={'ordering': ['-ra_date', 'fisher', 'net_set', 'net_num'], 'verbose_name': '(ICHP) RA Fishing Event', 'verbose_name_plural': '(ICHP) RA Fishing Events'},
        ),
        migrations.RemoveField(
            model_name='raevent',
            name='set_num',
        ),
        migrations.AddField(
            model_name='raevent',
            name='net_num',
            field=models.SmallIntegerField(db_comment='Net or net-set number.', db_default=1, default=1, verbose_name='Net #.'),
        ),
        migrations.AddField(
            model_name='raevent',
            name='net_set',
            field=models.SmallIntegerField(db_comment='Net or net-set number.', default=1, verbose_name='Set #.'),
            preserve_default=False,
        ),
    ]
