# Generated by Django 5.2.9 on 2025-12-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0008_alter_racatch_options_alter_raevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raevent',
            name='net_num',
            field=models.SmallIntegerField(db_comment='Net or net-set number.', verbose_name='Net #.'),
        ),
    ]
