# Generated by Django 5.2.9 on 2025-12-18 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0009_alter_raevent_net_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsample',
            name='basin',
            field=models.ForeignKey(db_comment='ID of river basin where fishing was conducted.', default=1, on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.basin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsample',
            name='pool',
            field=models.ForeignKey(db_comment='ID of pool where fishing was conducted.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.pool'),
        ),
    ]
