# Generated by Django 5.2.9 on 2026-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0010_subsample_basin_alter_subsample_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='raevent',
            name='water_depth_ft',
            field=models.DecimalField(blank=True, db_comment='Water depth (in feet) recorded during the ride-along event.', decimal_places=1, max_digits=3, null=True, verbose_name='Water Depth (ft)'),
        ),
        migrations.AddField(
            model_name='raevent',
            name='water_temp_f',
            field=models.DecimalField(blank=True, db_comment='Water temperature (F) recorded during the ride-along event.', decimal_places=1, max_digits=4, null=True, verbose_name='Water Temp (F)'),
        ),
        migrations.AlterField(
            model_name='cfcatch',
            name='healthy_cnt',
            field=models.IntegerField(blank=True, db_comment='Number of heathy bycatch caught and released during the contract fishing event.', null=True, verbose_name='Healthy Count'),
        ),
        migrations.AlterField(
            model_name='cfcatch',
            name='moribund_cnt',
            field=models.IntegerField(blank=True, db_comment='Number of moribund bycatch and/or harvested Invasive Carp caught during the contract fishing event.', null=True, verbose_name='Moribund Count'),
        ),
        migrations.AlterField(
            model_name='cfcatch',
            name='total_cnt',
            field=models.IntegerField(blank=True, db_comment='Total count of bycatch and Invasive carp caught during the contract fishing event.', null=True, verbose_name='Total Catch'),
        ),
        migrations.AlterField(
            model_name='iccatch',
            name='fish_count',
            field=models.SmallIntegerField(blank=True, db_comment='Total number of sampled fish.', null=True, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='racatch',
            name='healthy_cnt',
            field=models.IntegerField(blank=True, db_comment='Number of heathy bycatch caught and released during a ICHP ride-along effort.', null=True, verbose_name='Healthy Count'),
        ),
        migrations.AlterField(
            model_name='racatch',
            name='moribund_cnt',
            field=models.IntegerField(blank=True, db_comment='Number of moribund bycatch and/or harvested Invasive Carp caught during a ICHP ride-along effort.', null=True, verbose_name='Moribund Count'),
        ),
        migrations.AlterField(
            model_name='racatch',
            name='total_cnt',
            field=models.IntegerField(blank=True, db_comment='Total count of bycatch and Invasive carp caught during the ICHP ride-along effort.', null=True, verbose_name='Total Catch'),
        ),
    ]
