# Generated by Django 5.2.9 on 2026-01-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0011_raevent_water_depth_ft_raevent_water_temp_f_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icevent',
            name='air_temp_f',
            field=models.DecimalField(blank=True, db_comment='Air temperature (F) during the sampling effort.', decimal_places=1, max_digits=4, null=True, verbose_name='Air Temp (F)'),
        ),
        migrations.AddField(
            model_name='icevent',
            name='bankside',
            field=models.CharField(blank=True, choices=[('left descending', 'LDB'), ('right descending', 'RDB')], db_comment='Side of a river/stream/creek bank where a sampling effort was conducted.', max_length=20, null=True, verbose_name='Bank Side'),
        ),
        migrations.AddField(
            model_name='icevent',
            name='dipper_cnt',
            field=models.IntegerField(blank=True, db_comment='Number of dippers used during an electrofishing effort.', null=True, verbose_name='Dipper Count'),
        ),
        migrations.AddField(
            model_name='icevent',
            name='run_distance',
            field=models.DecimalField(blank=True, db_comment='Estimated bank distance of an electrofishing transect.', decimal_places=2, max_digits=6, null=True, verbose_name='Bank Distance (ft)'),
        ),
        migrations.AddField(
            model_name='icevent',
            name='weather',
            field=models.CharField(blank=True, choices=[('sunny', 'Sunny'), ('partly sunny', 'Partly Sunny'), ('overcast', 'Overcast'), ('rain', 'Rain'), ('fog', 'Fog'), ('snow', 'Snow')], db_comment='General weather conditions observed during the sampling effort.', max_length=20, null=True, verbose_name='Weather Cond.'),
        ),
        migrations.AddField(
            model_name='icevent',
            name='wind_speed_mph',
            field=models.DecimalField(blank=True, db_comment='Wind speed (mph) during the sampling effort.', decimal_places=2, max_digits=5, null=True, verbose_name='Wind Speed (mph)'),
        ),
    ]
