# Generated by Django 5.2.9 on 2026-01-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0012_icevent_air_temp_f_icevent_bankside_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racatch',
            old_name='healthy_cnt',
            new_name='rel_healthy_cnt',
        ),
        migrations.RemoveField(
            model_name='racatch',
            name='moribund_cnt',
        ),
        migrations.AddField(
            model_name='racatch',
            name='harvest_cnt',
            field=models.IntegerField(blank=True, db_comment='Number of Invasive Carp or other commercial species harvested during a ICHP ride-along effort.', null=True, verbose_name='Harvested Count'),
        ),
        migrations.AddField(
            model_name='racatch',
            name='rel_moribund_cnt',
            field=models.IntegerField(blank=True, db_comment='Number of moribund bycatch caught and released during a ICHP ride-along effort.', null=True, verbose_name='Moribund Count'),
        ),
    ]
