# Generated by Django 5.2.9 on 2026-01-12 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0013_rename_healthy_cnt_racatch_rel_healthy_cnt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IchpEvent',
            fields=[
                ('event_id', models.AutoField(db_comment='ID representing the ICHP fishing effort.', primary_key=True, serialize=False, verbose_name='ID')),
                ('ichp_date', models.DateField(db_comment='Date at which the commercial fishing occurred.', verbose_name='RA Date')),
                ('net_haul', models.SmallIntegerField(db_comment='Net or net-set number.', verbose_name='Set #.')),
                ('gear_length', models.IntegerField(blank=True, db_comment='Total length in feet of the net used for this fishing effort.', null=True, verbose_name='Net Length (ft)')),
                ('gear_depth', models.IntegerField(blank=True, db_comment='Total Depth in feet of the net used for this fishing effort.', null=True, verbose_name='Net Depth (ft) ')),
                ('mesh_size', models.DecimalField(blank=True, db_comment='Mesh size in inches of the net used for this fishing effort.', decimal_places=2, max_digits=5, null=True, verbose_name='Mesh Size (in)')),
                ('observed', models.BooleanField(db_comment='Identifies if an angency observer was present during ichp fishing effort.)', db_default=False, default=False, verbose_name='Observed')),
                ('latitude', models.DecimalField(blank=True, db_comment='Latitude of specific location where fishing gear was deployed.', decimal_places=5, max_digits=8, null=True, verbose_name='Net LAT')),
                ('longitude', models.DecimalField(blank=True, db_comment='Longitude of specific location where fishing gear was deployed.', decimal_places=5, max_digits=8, null=True, verbose_name='Net LON')),
                ('start_time', models.TimeField(blank=True, db_comment='Time of when the net was deployed.', null=True, verbose_name='Set Time')),
                ('end_time', models.TimeField(blank=True, db_comment='Time of when the net was retrieved.', null=True, verbose_name='Pull Time')),
                ('added_on', models.DateTimeField(auto_now_add=True, db_comment='Date-time of data input.')),
                ('added_by', models.CharField(blank=True, db_comment='name of person inputting the data.', max_length=150, null=True)),
                ('basin', models.ForeignKey(db_comment='ID of river basin or waterbody where commercial fishing effort was conducted.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.basin')),
                ('datez', models.ForeignKey(db_comment='ID referencing the date table for the ride-along date.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.dates')),
                ('fisher', models.ForeignKey(db_comment='ID of commercial fisher that completed the fishing efforts.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.fisher')),
                ('gear', models.ForeignKey(db_comment='ID of the gear type used to conduct the commercial fishing.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.gear')),
                ('site', models.ForeignKey(db_comment='ID of the specific location where the commercial fishing effort occured.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.fishingsite_hp')),
            ],
            options={
                'verbose_name': '(ICHP) Fishing Effort',
                'verbose_name_plural': '(ICHP) Fishing Efforts',
                'db_table': 'ichp_events',
                'db_table_comment': 'Information about the efforts that commercial fishers submitted to the KDFWR Invasive Carp Harvested Program.',
                'ordering': ['-ichp_date', 'fisher', 'net_haul'],
            },
        ),
    ]
