# Generated by Django 5.2.9 on 2026-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0014_ichpevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichpevent',
            name='observed',
            field=models.BooleanField(db_comment='Identifies if an angency observer was present during ichp fishing effort.)', verbose_name='Observed'),
        ),
    ]
