# Generated by Django 5.2.9 on 2026-01-13 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0015_alter_ichpevent_observed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ichpevent',
            options={'ordering': ['-ichp_date', 'fisher', 'net_haul'], 'verbose_name': '(ICHP) Fisher Effort', 'verbose_name_plural': '(ICHP) Fisher Efforts'},
        ),
        migrations.AlterField(
            model_name='ichpevent',
            name='net_haul',
            field=models.SmallIntegerField(db_comment='Net or net-set number.', verbose_name='Net Haul'),
        ),
        migrations.CreateModel(
            name='IchpCatch',
            fields=[
                ('catch_id', models.AutoField(db_comment='ID representing the catch results provided by commercial fishers ICHP Daily Harvest Report.', primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_healthy_cnt', models.IntegerField(blank=True, db_comment='Total healthy caught and released bycatch that was reported by the commercial fisher.', null=True, verbose_name='Healthy C&R')),
                ('rel_moribund_cnt', models.IntegerField(blank=True, db_comment='Total moribund caught and released bycatch that was reported by the commercial fisher.', null=True, verbose_name='Moribund C&R')),
                ('harvest_cnt', models.IntegerField(blank=True, db_comment='Total Invasive Carp (or other fish species) reported as harvested by the commercial fisher.', null=True, verbose_name='Total Harvested')),
                ('total_cnt', models.IntegerField(blank=True, db_comment='Total overall count of a fish species that was reported by the commercial fisher.', null=True, verbose_name='Total Caught')),
                ('reported_weight_lb', models.DecimalField(blank=True, db_comment='Total weight (lbs) of the harvested target species as reported by the commercial fisher.', decimal_places=2, max_digits=10, null=True, verbose_name='Reported TW (lb)')),
                ('reported_mean_length_in', models.DecimalField(blank=True, db_comment='Mean Length (in) of an Invasive Carp species that was subsampled and reported by the commercial fisher.', decimal_places=1, max_digits=5, null=True, verbose_name='Reported Mean Len (in)')),
                ('calc_mean_weight_g', models.DecimalField(blank=True, db_comment='Mean weight (g) of the harvested IC that was calculated from the harvest counts and Total weights reported by the commercial fisher.', decimal_places=1, max_digits=7, null=True, verbose_name='Calculated Mean Wgt (g)')),
                ('ss_code', models.CharField(blank=True, db_comment='Subsample identifier compiled from date, fisher_id and species_id (as YYYYMMDD.fid.sppid).', max_length=25, null=True, verbose_name='Subsample Code')),
                ('ss_mean_length_mm', models.DecimalField(blank=True, db_comment='Mean length (mm) of the harvested IC that was estimated from a subsample collected during an ICHP Ride-Along event.', decimal_places=1, max_digits=5, null=True, verbose_name='Est Mean Len (mm)')),
                ('ss_mean_weight_g', models.DecimalField(blank=True, db_comment='Mean weight (g) of the harvested IC that was estimated from a subsample collected during an ICHP Ride-Along event.', decimal_places=1, max_digits=7, null=True, verbose_name='Est Mean Wgt (g)')),
                ('predicted_mean_weight_g', models.DecimalField(blank=True, db_comment='Predicted mean weight (g) of the harvested carp calculated using a LxW regression equation that was generated from subsampled fish.', decimal_places=1, max_digits=7, null=True, verbose_name='Predicted Mean Wgt (g)')),
                ('added_on', models.DateTimeField(auto_now_add=True, db_comment='Date-time of data input.')),
                ('added_by', models.CharField(blank=True, db_comment='username of person inputting the data.', max_length=150, null=True)),
                ('event', models.ForeignKey(db_comment='ID representing a commercial fishing effort that was reported to the Invasive Carp Harvest Program.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.ichpevent')),
                ('species', models.ForeignKey(db_comment='ID of a fish species included in the ICHP Daily Report.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.fishspecies')),
            ],
            options={
                'verbose_name': '(ICHP) Harvest Data',
                'verbose_name_plural': '(ICHP) Harvest Data',
                'db_table': 'ichp_catch',
                'db_table_comment': 'Catch Results from ICHP Daily Harvest reports provided by a participating commercial fisher.',
                'ordering': ['-event__ichp_date', 'event__fisher', 'event__net_haul'],
            },
        ),
    ]
