# Generated by Django 5.2.9 on 2026-01-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0016_alter_ichpevent_options_alter_ichpevent_net_haul_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ichpcatch',
            name='reported_weight_lb',
            field=models.DecimalField(blank=True, db_comment='Total weight (lbs) of the harvested target species as reported by the commercial fisher.', decimal_places=1, max_digits=10, null=True, verbose_name='Reported TW (lb)'),
        ),
    ]
