# Generated by Django 5.2.9 on 2026-01-21 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0017_alter_ichpcatch_reported_weight_lb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsample',
            name='basin',
            field=models.ForeignKey(db_comment='ID of river basin where fishing was conducted.', db_default=1, on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.basin'),
        ),
    ]
