# Generated by Django 5.2.9 on 2026-02-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0018_alter_subsample_basin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_id'], 'verbose_name': '(Lookup) Project', 'verbose_name_plural': '(Lookup) Projects'},
        ),
    ]
