# Generated by Django 5.2.9 on 2026-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0019_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icevent',
            name='bankside',
            field=models.CharField(blank=True, choices=[('left descending', 'LDB/RAB'), ('right descending', 'RDB/LAB')], db_comment='Side of a river/stream/creek bank where a sampling effort was conducted.', max_length=20, null=True, verbose_name='Bank Side'),
        ),
        migrations.AlterField(
            model_name='icevent',
            name='effort_min',
            field=models.DecimalField(blank=True, db_comment='Length of time in minutes that the sampling effort occured for.', decimal_places=2, max_digits=8, null=True, verbose_name='Effort (min)'),
        ),
        migrations.AlterField(
            model_name='icevent',
            name='run_distance',
            field=models.DecimalField(blank=True, db_comment='Estimated bank distance of an electrofishing transect.', decimal_places=3, max_digits=6, null=True, verbose_name='Bank Distance (mi)'),
        ),
    ]
