# Generated by Django 5.2.9 on 2026-03-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0020_alter_icevent_bankside_alter_icevent_effort_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='targeted',
            field=models.BooleanField(db_comment='Indicates if the species is targeted by invasive carp removal efforts.', db_default=False, default=False, verbose_name='Targeted'),
        ),
    ]
