# Generated by Django 5.2.9 on 2026-03-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0021_fishspecies_targeted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='cf_season',
            field=models.CharField(blank=True, db_comment='Season breakdown for contract fishing only.', max_length=10, null=True, verbose_name='Season_2'),
        ),
    ]
