# Generated by Django 5.2.9 on 2026-05-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0022_dates_cf_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fisher',
            name='past_violations',
        ),
        migrations.RemoveField(
            model_name='fisher',
            name='phone',
        ),
    ]
