# Generated by Django 5.2.9 on 2026-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0023_remove_fisher_email_remove_fisher_past_violations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basin',
            name='boundary',
            field=models.JSONField(blank=True, db_comment='GeoJSON Polygon or MultiPolygon defining the basin boundary.', null=True, verbose_name='Boundary'),
        ),
        migrations.AddField(
            model_name='pool',
            name='boundary',
            field=models.JSONField(blank=True, db_comment='GeoJSON Polygon or MultiPolygon defining the pool boundary.', null=True, verbose_name='Boundary'),
        ),
        migrations.AddField(
            model_name='trib',
            name='boundary',
            field=models.JSONField(blank=True, db_comment='GeoJSON Polygon or MultiPolygon defining the tributary boundary.', null=True, verbose_name='Boundary'),
        ),
    ]
