# Generated by Django 5.2.9 on 2026-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0024_basin_boundary_pool_boundary_trib_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huc12',
            fields=[
                ('huc_id', models.AutoField(db_comment='ID representing the USGS HUC12 record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('huc12', models.CharField(db_comment='Official USGS ID number (11-digits) for the HUC12 location.', max_length=11, verbose_name='HUC12')),
                ('huc12_name', models.CharField(db_comment='Official name of the HUC12 location as designated by the USGS.', max_length=100, verbose_name='Name')),
                ('huc10', models.CharField(db_comment='Official USGS ID number (9-digits) for the HUC10 location that the HUC12 belongs to.', max_length=9, verbose_name='HUC10')),
                ('huc10_name', models.CharField(db_comment='Name of the HUC10 location that the HUC12 belongs to.', max_length=100, verbose_name='HUC10 Name')),
                ('huc8', models.CharField(db_comment='Official USGS ID number (7-digits) for the HUC8 location that the HUC12 belongs to.', max_length=7, verbose_name='HUC8')),
                ('huc8_name', models.CharField(db_comment='Name of the HUC8 location that the HUC12 belongs to.', max_length=100, verbose_name='HUC8 Name')),
                ('huc12_acres', models.DecimalField(blank=True, db_comment='Area of the HUC12 in acres.', decimal_places=2, max_digits=10, null=True, verbose_name='Area_acres')),
                ('huc12_sqkm', models.DecimalField(blank=True, db_comment='Area of the HUC12 in square kilometers.', decimal_places=2, max_digits=10, null=True, verbose_name='Area_sqkm')),
                ('boundary', models.JSONField(blank=True, db_comment='GeoJSON Polygon or MultiPolygon defining the HUC12 boundary.', null=True, verbose_name='Boundary')),
                ('last_update', models.DateTimeField(auto_now_add=True, db_comment='Date-time of creation.')),
            ],
            options={
                'verbose_name': '(Lookup) HUC12_USGS',
                'verbose_name_plural': '(Lookup) HUC12_USGS',
                'db_table': 'huc12',
                'db_table_comment': 'A list of the names and boundaries for all USGS HUC12 locations within Kentucky.',
            },
        ),
    ]
