# Generated by Django 5.2.9 on 2026-06-29 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0025_huc12'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverMile',
            fields=[
                ('rm_id', models.AutoField(db_comment='ID for a river mile location.', primary_key=True, serialize=False, verbose_name='ID')),
                ('mile', models.DecimalField(db_comment='River mile value for the location.', decimal_places=1, max_digits=6, verbose_name='River Mile')),
                ('latitude', models.DecimalField(db_comment='Latitude coordinate for the river mile location.', decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(db_comment='Longitude coordinate for the river mile location.', decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('point', models.JSONField(blank=True, db_comment='GeoJSON point for the river mile location.', null=True, verbose_name='Point')),
                ('last_update', models.DateTimeField(auto_now=True, db_comment='Date-time of creation or update.')),
                ('basin', models.ForeignKey(db_comment='Foreign key to the basin for the river mile location.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.basin')),
                ('pool', models.ForeignKey(db_comment='Foreign key to the pool for the river mile location.', on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.pool')),
            ],
            options={
                'verbose_name': '(Lookup) River Mile',
                'verbose_name_plural': '(Lookup) River Miles',
                'db_table': 'river_mile',
                'db_table_comment': 'River mile locations within the Ohio River and Mississippi Basins.',
            },
        ),
    ]
