# Generated by Django 5.2.9 on 2026-06-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0026_rivermile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rivermile',
            old_name='point',
            new_name='rm_point',
        ),
    ]
