# Generated by Django 5.2.9 on 2026-06-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0027_rename_point_rivermile_rm_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['priority'], 'verbose_name': '(Lookup) Gear', 'verbose_name_plural': '(Lookup) Gear'},
        ),
        migrations.AddField(
            model_name='gear',
            name='priority',
            field=models.SmallIntegerField(blank=True, db_comment='Priority of the fish sampling gear type.', null=True, verbose_name='Priority'),
        ),
    ]
