# Generated by Django 5.2.9 on 2026-07-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0028_alter_gear_options_gear_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='active',
            field=models.BooleanField(db_comment='Identifies if the crew is currently active in the program.', db_default=True, default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='fisher',
            name='active',
            field=models.BooleanField(db_comment='Identifies if the contract fisher is currently active in the program.', db_default=True, default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='observer',
            name='active',
            field=models.BooleanField(db_comment='Identifies if the agency observer is currently active in the program.', db_default=True, default=True, verbose_name='Active'),
        ),
    ]
