# Generated by Django 5.2.9 on 2026-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0029_crew_active_fisher_active_observer_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisher',
            options={'ordering': ('-active', 'last_name', 'first_name'), 'verbose_name': '(Lookup) Fisher', 'verbose_name_plural': '(Lookup) Fishers'},
        ),
        migrations.AlterModelOptions(
            name='observer',
            options={'ordering': ('-active', 'last_name', 'first_name'), 'verbose_name': '(CF) Observer', 'verbose_name_plural': '(CF) Observers'},
        ),
        migrations.AlterField(
            model_name='partner',
            name='abbrev',
            field=models.CharField(db_comment='Abbreviation of the agency or institution.', max_length=10, verbose_name='Abbrev'),
        ),
    ]
