# Generated by Django 5.2.9 on 2026-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0030_alter_fisher_options_alter_observer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_comment='Name of the ORB Invasive Carp Project.', max_length=40, verbose_name='Name'),
        ),
    ]
