# Generated by Django 5.2.9 on 2026-09-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0031_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingsite_hp',
            name='latitude',
            field=models.DecimalField(db_comment='Latitude of the commercial fishing location.', decimal_places=6, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='fishingsite_hp',
            name='longitude',
            field=models.DecimalField(db_comment='Longitude of the commercial fishing location.', decimal_places=6, max_digits=9, verbose_name='Longitude'),
        ),
    ]
