# Generated by Django 5.2.9 on 2026-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0032_alter_fishingsite_hp_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingsite_cf',
            name='latitude',
            field=models.DecimalField(db_comment='Latitude of the contract fishing location.', decimal_places=6, max_digits=9, verbose_name='Site LAT'),
        ),
        migrations.AlterField(
            model_name='fishingsite_cf',
            name='longitude',
            field=models.DecimalField(db_comment='Longitude of the contract fishing location.', decimal_places=6, max_digits=9, verbose_name='Site LON'),
        ),
        migrations.AlterField(
            model_name='samplesite',
            name='latitude',
            field=models.DecimalField(blank=True, db_comment='Latitude of the sampling site location.', decimal_places=6, max_digits=9, null=True, verbose_name='Site LAT'),
        ),
        migrations.AlterField(
            model_name='samplesite',
            name='longitude',
            field=models.DecimalField(blank=True, db_comment='Longitude of the sampling site location.', decimal_places=6, max_digits=9, null=True, verbose_name='Site LON'),
        ),
    ]
