# Generated by Django 5.2.9 on 2026-10-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0033_alter_fishingsite_cf_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icevent',
            name='gear',
            field=models.ForeignKey(db_comment='ID of gear type used during the sampling effort.', default=21, on_delete=django.db.models.deletion.PROTECT, to='kiccd_app.gear'),
            preserve_default=False,
        ),
    ]
