# Generated by Django 5.2.9 on 2026-10-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiccd_app', '0034_alter_icevent_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplesite',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='sample_sites', to='kiccd_app.project', verbose_name='Projects'),
        ),
    ]
