"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from urllib.parse import urlparse, parse_qsl
from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APP_DIR = BASE_DIR / 'kiccd_app'
FROZEN = getattr(sys, "frozen", False)
BUNDLE_DIR = Path(getattr(sys, "_MEIPASS", BASE_DIR))
APP_BUNDLE_DIR = BUNDLE_DIR / "kiccd_app"


# Load environment variables from .env file
dotenv_paths = [BASE_DIR / ".env"]
if FROZEN:
    dotenv_paths.append(Path(sys.executable).resolve().parent / ".env")
for dotenv_path in dotenv_paths:
    load_dotenv(dotenv_path, override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY')

# DEBUG = os.getenv('DEBUG') == 'True'
DEBUG = False

# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS').split(',')
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '*']

# Mapbox
MAPBOX_TOKEN = os.getenv('MAPBOX_TOKEN', '')

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'django.forms',
    'kiccd_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            APP_DIR / 'templates',
            *( [APP_BUNDLE_DIR / 'templates'] if FROZEN else [] ),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kiccd_app.context_processors.mapbox_token',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

tmpPg= urlparse(os.getenv('DATABASE_URL'))

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': tmpPg.path.replace('/', ''),
#         'USER': tmpPg.username,
#         'PASSWORD': tmpPg.password,
#         'HOST': tmpPg.hostname,
#         'PORT': 5432,
#         'OPTIONS': dict(parse_qsl(tmpPg.query)),
#         # Neon pooler/pgbouncer transaction pooling does not support server-side cursors.
#         'DISABLE_SERVER_SIDE_CURSORS': True,
#     }
# }
  
# Local version of database for development
 
DATABASES = {
 'default': {
 	'ENGINE': 'django.db.backends.postgresql',
 	'NAME': 'kiccd_dj',
 	'USER': 'postgres',
 	'PASSWORD': 'root',
 	'HOST': 'localhost',
 	'PORT': 5432,
    'DISABLE_SERVER_SIDE_CURSORS': True,
 	}
 }

#  
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
 

STATIC_URL = "static/"
STATIC_ROOT = str(APP_DIR / "staticfiles")
STATICFILES_DIRS = [str(APP_DIR / "static")]
if FROZEN:
    STATICFILES_DIRS.append(str(APP_BUNDLE_DIR / "staticfiles"))
WHITENOISE_USE_FINDERS = True

# https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
MEDIA_URL = "media/"
MEDIA_ROOT = APP_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT') == 'True'
# SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE') == 'True'
# CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE') == 'True'
# SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 31536000))  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS') == 'True'
# SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD') == 'True'
# SECURE_BROWSER_XSS_FILTER = os.getenv('SECURE_BROWSER_XSS_FILTER') == 'True'
# SECURE_CONTENT_TYPE_NOSNIFF = os.getenv('SECURE_CONTENT_TYPE_NOSNIFF') == 'True'
# X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY'


if FROZEN:
    log_dir = Path(sys.executable).resolve().parent / "kiccd_logs"
    try:
        log_dir.mkdir(parents=True, exist_ok=True)
    except OSError:
        log_dir = Path.cwd()

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {name} {message}",
                "style": "{",
            }
        },
        "handlers": {
            "file": {
                "level": "ERROR",
                "class": "logging.FileHandler",
                "filename": str(log_dir / "app_errors.log"),
                "formatter": "verbose",
            }
        },
        "loggers": {
            "django": {
                "handlers": ["file"],
                "level": "ERROR",
                "propagate": True,
            },
            "django.request": {
                "handlers": ["file"],
                "level": "ERROR",
                "propagate": False,
            },
        },
    }
