from django.urls import path
from .views import (IchpHarvestListView, ProjectListView, PoolListView, RecentIcCatchView, SpeciesListView, BasinListView, 
                    GearListView, CrewListView, FisherListView, ObserverListView, CfCatchListView, IcCatchListView, RaCatchListView,
                    IcAgeGrowthListView)
from . import views as _views

app_name = 'kiccd_app'

urlpatterns = [
    path('register/', view=_views.register_view, name='register'),
    path('login/', view=_views.login_view, name='login'),
    path('logout/', view=_views.logout_view, name='logout'),
    path('home/', view=_views.home_view, name='home'),
    path('', view=_views.root_page_view, name='root_page'),
    path('<str:template_name>/', view=_views.dynamic_pages_view, name='dynamic_pages'),

    path('maps/sites/', _views.site_map_view, name='site_map'),
    path('maps/site-check/', _views.site_check_view, name='site_check'),
    path('sampling/sites/', _views.sample_site_list, name='sample_sites'),
    path('sampling/sites/add/', _views.sample_site_create, name='sample_site_create'),
    path('sampling/events/add/', _views.ic_event_create, name='ic_event_create'),
    path('sampling/events/recent/', _views.recent_ic_events, name='recent_ic_events'),
    path('sampling/results/add/', _views.ic_catch_create, name='ic_catch_create'),
    path('sampling/combined-add/', _views.ic_combined_create, name='ic_combined_create'),
    path('sampling/results/', IcCatchListView.as_view(), name='ic_catch_list'),
    path('sampling/results/recent/', RecentIcCatchView.as_view(), name='recent_ic_catch'),
    path('sampling/ag/data/', IcAgeGrowthListView.as_view(), name='ic_age_growth_list'),
    path('sampling/ag/bulk-add/', _views.ic_age_growth_bulk_create, name='ic_age_growth_bulk_create'),
    
    path('fishing/contract/efforts/batch-add/', _views.cf_event_batch_create, name='cf_event_batch_create'),
    path('fishing/contract/efforts/add/', _views.cf_event_create, name='cf_event_create'),
    path('fishing/contract/catch/add/', _views.cf_catch_batch_create, name='cf_catch_batch_create'),
    path('fishing/contract/catch/list/', CfCatchListView.as_view(), name='cf_catch_list'),
    path('fishing/contract/efforts/recent/', _views.recent_cf_events, name='recent_cf_events'),

    path('fishing/ichp/ra/events/set-add/', _views.ra_event_set_create, name='ra_event_set_create'),
    path('fishing/ichp/ra/events/add/', _views.ra_event_create, name='ra_event_create'),
    path('fishing/ichp/ra/catch/add/', _views.ra_catch_batch_create, name='ra_catch_batch_create'),
    path('fishing/ichp/ra/catch/list/', RaCatchListView.as_view(), name='ra_catch_list'),
    path('fishing/ichp/ra/events/recent/', _views.recent_ra_events, name='recent_ra_events'),
    
    path('fishing/ichp/fisher_reports/set-add/', _views.ichp_event_create, name='ichp_event_set_create'),
    path('fishing/ichp/fisher_reports/combined-add/', _views.ichp_event_and_catch_create, name='ichp_event_and_catch_create'),
    path('fishing/ichp/fisher_reports/recent/', _views.recent_ichp_events, name='recent_ichp_events'),
    path('fishing/ichp/fisher_reports/harvest/list/', IchpHarvestListView.as_view(), name='ichp_harvest_list'),
    path('fishing/ichp/fisher_reports/harvest/add/', _views.ichp_catch_batch_create, name='ichp_catch_batch_create'),

    path('fishing/subsamples/bulk-add/', _views.subsample_bulk_create, name='subsample_bulk_create'),
    path('fishing/subsamples/', _views.SubsampleListView.as_view(), name='subsample_data'),
    path('fishing/subsamples/filtered/', _views.subsample_filtered_view, name='subsample_filtered'),
    path('fishing/cf_sites/', _views.cf_site_list, name='cf_sites'),
    path('fishing/cf_sites/add/', _views.fishing_site_cf_create, name='cf_site_create'),
    path('fishing/hp_sites/add/', _views.fishing_site_hp_create, name='hp_site_create'),
    path('fishing/hp_sites/', _views.hp_site_list, name='hp_sites'),
    path('lookup/tributaries/', _views.trib_list, name='trib_list'),
    path('lookup/pools/', PoolListView.as_view(), name='pool_list'),
    path('lookup/collections/', _views.lookup_collections, name='lookup_collections'),
    path('lookup/species/', SpeciesListView.as_view(), name='species_list'),
    path('lookup/basins/', BasinListView.as_view(), name='basin_list'),
    path('lookup/crews/', CrewListView.as_view(), name='crew_list'),
    path('lookup/gear/', GearListView.as_view(), name='gear_list'),
    path('lookup/projects/', ProjectListView.as_view(), name='project_list'),
    path('lookup/fishers/', FisherListView.as_view(), name='fisher_list'),
    path('lookup/observers/', ObserverListView.as_view(), name='observer_list'),
    path('fishers/add/', _views.fisher_create, name='fisher_create'),
    path('observers/add/', _views.observer_create, name='observer_create'),
    path('crews/add/', _views.crew_create, name='crew_create'),
    path('api/crews/add/', _views.crew_create_ajax, name='crew_create_ajax'),
    path('tribs/add/', _views.trib_create, name='trib_create'),
   
    # App Features
    path('fishing/ichp/ra/refresh-means/', _views.ra_catch_refresh_subsample_means, name='refresh_racatch_means'),
    path('fishing/contract/refresh-means/', _views.cf_refresh_subsample_means, name='refresh_cfcatch_means'),
    path('fishing/ichp/refresh-means/', _views.ichp_refresh_subsample_means, name='refresh_ichpcatch_means'),

    # Stats/Results Pages
    path('sampling/catch/stats/', _views.ic_catch_stats, name='ic_catch_stats'),
    path('sampling/filtered/', _views.ic_filtered_view, name='ic_filtered'),
    path('sampling/ag/length-at-age/', _views.ic_age_growth_length_at_age, name='ic_age_growth_length_at_age'),
    path('fishing/cf/filtered/', _views.cf_filtered_results, name='cf_filtered'),
    path('fishing/cf/reports/filtered/', _views.cf_report_filtered_view, name='cf_report_filtered'),
    path('fishing/ichp/filtered/', _views.ichp_filtered_results, name='ichp_filtered'),
    path('fishing/ichp/reports/filtered/', _views.ichp_report_filtered_view, name='ichp_report_filtered'),
    path('fishing/ichp/ra/reports/filtered/', _views.ra_report_filtered_view, name='ra_report_filtered'),
    path('fishing/cf/monthly-charts/', _views.cf_charted_results, name='cf_charted_results'),
    path('fishing/ichp/monthly-weight/', _views.ichp_monthly_weight_chart, name='ichp_monthly_weight'),
    path('fishing/cf/daily-catch-rate/', _views.cf_daily_catch_rate, name='cf_daily_catch_rate'),
    path('fishing/ss/length-dist/', _views.subsample_length_distribution, name='ss_length_dist'),
    path('sampling/ic/length-dist/', _views.ic_length_distribution, name='ic_length_dist'),
    path('api/catch/yearly-totals/', _views.yearly_totals, name='catch_yearly_totals'),
    path('api/cf/fisher-days/', _views.cf_fisher_day_count, name='cf_fisher_day_count'),
    path('api/cf/harvest-stats/', _views.cf_harvest_stats, name='cf_harvest_stats'),
    path('api/cf/net-stats/', _views.cf_net_stats, name='cf_net_stats'),
    path('api/cf/effort-stats/', _views.cf_effort_stats, name='cf_effort_stats'),
    path('api/ichp/effort-stats/', _views.ichp_effort_stats, name='ichp_effort_stats'),
    path('api/ichp/harvest-stats/', _views.ichp_harvest_stats, name='ichp_harvest_stats'),
    path('api/ic/event-catch-count/', _views.ic_catch_count_by_event, name='api_ic_event_catch_count'),
    path('api/ic/event-catch-count/<int:event_id>/', _views.ic_catch_count_by_event, name='api_ic_event_catch_count_by_id'),
    path('api/ichp/event-search/', _views.ichp_event_search, name='api_ichp_event_search'),
    path('api/ichp/event-catch-count/', _views.ichp_catch_count_by_event, name='api_ichp_event_catch_count'),
    path('api/ichp/event-catch-count/<int:event_id>/', _views.ichp_catch_count_by_event, name='api_ichp_event_catch_count_by_id'),
    path('api/ra/event-catch-count/', _views.ra_catch_count_by_event, name='api_ra_event_catch_count'),
    path('api/ra/event-catch-count/<int:event_id>/', _views.ra_catch_count_by_event, name='api_ra_event_catch_count_by_id'),
    path('api/cf/event-catch-count/', _views.cf_catch_count_by_event, name='api_cf_event_catch_count'),
    path('api/cf/event-catch-count/<int:event_id>/', _views.cf_catch_count_by_event, name='api_cf_event_catch_count_by_id'),
 
    # AJAX endpoints
    path('api/fishers/add/', _views.fisher_create_ajax, name='fisher_create_ajax'),
    path('api/observers/add/', _views.observer_create_ajax, name='observer_create_ajax'),
    path('api/cf-sites/add/', _views.cf_site_create_ajax, name='cf_site_create_ajax'),
    path('api/hp-sites/add/', _views.hp_site_create_ajax, name='hp_site_create_ajax'),
    path('api/sample-sites/add/', _views.sample_site_create_ajax, name='sample_site_create_ajax'),
    path('api/pools-by-basin/<int:basin_id>/', _views.pools_by_basin, name='api_pools_by_basin'),
    path('api/offices-by-agency/<int:agency_id>/', _views.offices_by_agency, name='api_offices_by_agency'),
    path('api/crews-by-agency/<int:agency_id>/', _views.crews_by_agency, name='api_crews_by_agency'),
    path('api/counties-by-state/<int:state_id>/', _views.counties_by_state, name='api_counties_by_state'),
    path('api/tribs-by-basin/<int:basin_id>/', _views.tribs_by_basin, name='api_tribs_by_basin'),
    path('api/tribs-by-basin-and-pool/<int:basin_id>/<int:pool_id>/', _views.tribs_by_basin_and_pool, name='api_tribs_by_basin_and_pool'),
    path('api/pool-boundaries/', _views.pool_boundaries, name='api_pool_boundaries'),
    path('api/basin-boundaries/', _views.basin_boundaries, name='api_basin_boundaries'),
    path('api/trib-boundaries/', _views.trib_boundaries, name='api_trib_boundaries'),
    path('api/river-mile-points/', _views.river_mile_points, name='api_river_mile_points'),
    path('api/huc12-boundaries/', _views.huc12_boundaries, name='api_huc12_boundaries'),
    path('api/fishing-sites-hp-by-basin/<int:basin_id>/', _views.FishingSites_HP_by_basin, name='api_fishing_sites_hp_by_basin'),
    path('api/sample-sites-by-basin/<int:basin_id>/', _views.SampleSite_by_basin, name='api_sample_sites_by_basin'),
    path('api/sample-sites-by-pool/<int:pool_id>/', _views.SampleSite_by_pool, name='api_sample_sites_by_pool'),
    path('api/sample-sites-by-basin-and-pool/<int:basin_id>/<int:pool_id>/', _views.SampleSite_by_basin_and_pool, name='api_sample_sites_by_basin_and_pool'),
    path('api/sample-sites-lookup/', _views.sample_sites_lookup, name='api_sample_sites_lookup'),
    path('api/sample-sites/geojson/', _views.sample_sites_geojson, name='api_sample_sites_geojson'),
    path('api/cf-sites/geojson/', _views.cf_sites_geojson, name='api_cf_sites_geojson'),
    path('api/hp-sites/geojson/', _views.hp_sites_geojson, name='api_hp_sites_geojson'),
    path('api/tribs/geojson/', _views.trib_sites_geojson, name='api_trib_sites_geojson'),

]
 